@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam ClassFontColor #000000
skinparam ClassBorderColor MODEL_COLOR
skinparam ClassBorderThickness 1.5

title After command "deleteClass B"

Package {
class "<u>:TeachBook</u>" as TeachBook
class "<u>:UniqueClassList</u>" as UniqueClassList

class "<u>A:Class</u>" as ClassA
class "<u>:UniqueStudentList</u>" as UniqueStudentListA

class "<u>Alice:Student</u>" as Alice
class "<u>Ann:Student</u>" as Ann
}

TeachBook *--> UniqueClassList
UniqueClassList --> ClassA
ClassA *--> UniqueStudentListA

UniqueStudentListA --> Alice
UniqueStudentListA --> Ann

@enduml
