@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTeachBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class ReadOnlyTeachBook
Class ReadOnlyUserPrefs
Class Model

Class TeachBook
Class UserPrefs
Class ModelManager

Class UniqueClassList
Class GeneralIndex
Class UniqueStudentList

Class Student
Class Name
Class Phone
Class Class
Class Address
Class Email
Class Tag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TeachBook .up.|> ReadOnlyTeachBook
ModelManager .up.|> Model
UserPrefs .up.|> ReadOnlyUserPrefs
Model .left.> ReadOnlyTeachBook
Model .right.> ReadOnlyUserPrefs

ModelManager -up-> "1" TeachBook
ModelManager -up-> "1" UserPrefs
ModelManager --> "~* filtered" Student
ModelManager -right-> "1 selected class" GeneralIndex

TeachBook *--> "1" UniqueClassList
UniqueClassList --> "~* all" Class
Class *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student

Student *--> "1" Name
Student *--> "1" Phone
Student --> "1" Class
Student *--> "1" Email
Student *--> "1" Address
Student *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

@enduml
