@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "TeachBook Storage" #F4F6F6{
Interface TeachBookStorage <<Interface>>
Class JsonTeachBookStorage
Class JsonSerializableTeachBook
Class JsonAdaptedGrade
Class JsonAdaptedClass
Class JsonAdaptedStudent
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TeachBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TeachBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTeachBookStorage .up.|> TeachBookStorage
JsonTeachBookStorage ..> JsonSerializableTeachBook
JsonSerializableTeachBook --> "*" JsonAdaptedGrade
JsonSerializableTeachBook --> "*" JsonAdaptedClass
JsonAdaptedClass --> "*" JsonAdaptedStudent
JsonAdaptedStudent --> "*" JsonAdaptedTag

@enduml
