@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TeachBookParser" as TeachBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTeachBook" as VersionedTeachBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> TeachBookParser : parseCommand(undo)
activate TeachBookParser

create UndoCommand
TeachBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> TeachBookParser
deactivate UndoCommand

TeachBookParser --> LogicManager : u
deactivate TeachBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoAddressBook()
activate Model

Model -> VersionedTeachBook : undo()
activate VersionedTeachBook

VersionedTeachBook -> VersionedTeachBook :resetData(ReadOnlyTeachBook)
VersionedTeachBook --> Model : TeachBookDisplayState
deactivate VersionedTeachBook

activate Model
Model -> Model : updateCurrentlySelectedClass(GeneralIndex)
Model -> Model : updateFilteredStudentList(Predicate<Student>)

deactivate Model
Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
